# Generated by Django 3.2.4 on 2021-07-24 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('timing', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
