# Generated by Django 3.2.4 on 2021-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='agent_name',
            field=models.CharField(choices=[('avesh', 'Avesh'), ('ajay', 'Ajay')], default='avesh', max_length=10),
        ),
    ]
