# Generated by Django 3.2.4 on 2021-07-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0002_alter_sells_agent_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='agent_name',
            field=models.CharField(max_length=10),
        ),
    ]
