# Generated by Django 3.2.4 on 2021-07-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0003_alter_sells_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sells',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
